### ISSUE TITLE
Save jobs when they finish successfully

### ISSUE THREAD

**Issue by jerson** [fireworq/fireworq#10]
Hello, I was wondering if it is possible to save the job when they finish and the result is successful, now I think they are eliminated, but for example: if I need to keep track of the job that results successful and the result of each job means something useful to verify .

maybe I could have an option that saves the successful jobs for a period of time and then it is eliminated, that would help not to save a lot of data in the database.

pd: Merry Christmas :santa:

**Comment by tarao** [comment]
The reason why we have failed jobs saved but successfully finished jobs not saved is that it is enough if you save the results of successfully finished jobs by your own on the worker side but this is not always possible for failed ones. For example, they might fail because the connection to the worker is lost. Tracking failed jobs on the queue side is necessary while tracking successful ones just may be useful.

Anyway, I agree that it is useful if we can track successful results just like failed ones.  And an option to eliminate old results could also apply to the failure log.  I will think about a good way to achieve this.

**Comment by uchan-nos** [comment]
I agree with jerson. I want Fireworq to have facility to save status of successed and permanently-failed jobs.

It's true that data size will increase infinitely if status of all jobs are saved forever. It's not suitable for production use.
To avoid this, I like Apache Kafua's approach, which retains logs for configured duration even if the logs are consumed by consumers.
Kafka deletes logs if the time passed configured duration, or the size of logs exceed configured capacity.

**Comment by uchan-nos** [comment]
After some digging, I've noted that I can decide whether a job has been succeeded or not without adding any feature to Fireworq.

Because Fireworq's failure log records failed and permanently-failed jobs, I can use following steps to decide whether a job has been succeeded or failed (and will not be retried any more):

1. Wait for a job to be removed from `/queue/{queue_name}/job/{id}`.
2. Get `/queue/{queue_name}/failed/{id}`
3. If the status = 200, the job has been **failed** (and will not be retried any more).
4. If the status = 404, the job has been **succeeded**.
