### ISSUE TITLE
Keep queued joobs when backend is down

### ISSUE THREAD

**Issue by pablolagos** [fireworq/fireworq#40]
When the backend is down, jobs are marked as internal-failure and they are removed from the queue.

The expected behavior is to keep the job in the queue and try again later until the backend server could be reached.

**Comment by tarao** [comment]
Specifying `max_retries` will prevent jobs from being removed from queue when the backend is down.  You should also specify `retry_delay` in this case. For example, specifying `"max_retries": 5` and `"retry_delay": 60` will make it automatically rcover from five-minutes server down.

We are not going to add any other retrying mechanism specific to server down because it is hard to distinguish server down from other malfunction.  For example, if your backend is behind an nginx host (which may be a sidecar of the backend), then `504` or `502` will be returned rather than a socket error.  These HTTP responses may be returned if the backend is not down but some other micro-service is malfunctioning.

You should provide a way to distinguish server down from other errors and reason why it should be distinguished, or otherwise we won't treat it  specially.
